blog/urls.py
from django.urls import path
from .views import (
    PostDetailView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
   
    
)
from blog import views as blog_views


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog_home'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('like/<int:pk>', blog_views.LikeView, name='like_post'),
    
]

results/urls.py
from django.urls import path
#from wkhtmltopdf.views import PDFTemplateView
#from wkhtmltopdf import PDFTemplateView
# from wkhtmltopdf import WKHtmlToPdf
from django.conf.urls.static import static
from results import views as result_views 
from django.contrib.auth import views as auth_views
from . import views
from .views import  ResultDetailView, ResultDetail2View, ResultDetail3View, ResultUpdateView, ResultUpdateView2, ResultUpdateView3
# from . import views

app_name = 'results'

urlpatterns = [
    path('print-result/', result_views.printresult, name="print-result"),
    path('print-second-result/', result_views.printresult2, name="print-second-result"),
    path('print-third-result/', result_views.printresult3, name="print-third-result"), 

    path('result-sheet/', result_views.resultsheet, name="result-sheet"),
    path('result-create/', result_views.result_create_form, name="result-create"),

    path('my-result/', result_views.view_self_result, name="my-result"),
    path('mysecond-term-result/', result_views.view_self_result2, name="mysecond-term-result"),
    path('mythird-term-result/', result_views.view_self_result3, name="mythird-term-result"),

    path('print-resultform/', result_views.printresultform, name="print-resultform"),
    path('upload-result/', result_views.uploadresult, name="upload-result"),
   
    path('my-reportsheet/', result_views.view_self_reportsheet, name="my-reportsheet"),

    # Results Update Views
    path('<int:id>/result-update/', ResultUpdateView.as_view(), name="result-update"),
    path('<int:id>/second-result-update/', ResultUpdateView2.as_view(), name="second-result-update"),
    path('<int:id>/third-result-update/', ResultUpdateView3.as_view(), name="third-result-update"),

    # # Results List Views
    # path('result-list/', ResultListView.as_view(), name='result-list'),
    # path('second-result-list/', ResultListView2.as_view(), name='second-result-list'),
    # path('third-result-list/', ResultListView3.as_view(), name='third-result-list'),

    # Results Detail Views
    path('<int:pk>/', ResultDetailView.as_view(), name='result-detail'), 
    path('<int:pk>/second-term/', ResultDetail2View.as_view(), name='second-term-detail'), 
    path('<int:pk>/third-term/', ResultDetail3View.as_view(), name='third-term-detail'), 

    # Results CSV FORMAT URLS
    path('result-csv', result_views.results_csv, name="result-csv"),
    path('second-result-csv', result_views.results_csv_2, name="second-result-csv"),
    path('third-result-csv', result_views.results_csv_3, name="third-result-csv"),
 
    # render resultsheet as pdf
    path('pdf/<pk>/', result_views.result_render_pdf_view, name="result-pdf-view"),
    path('pdf/<pk>/second-term/', result_views.result2_render_pdf_view, name="second-result-pdf-view"),
    path('pdf/<pk>/third-term/', result_views.result3_render_pdf_view, name="third-result-pdf-view"),
    #path('results/', PDFTemplateView.as_view(template_name='results/result_sheet.html',
    #                                       filename='my_result.pdf'), name='result-pdf'),

    #path to form-teachers class results
    path('my-student-results-first/', result_views.self_student_results_firsterm, name="my-students-results-first"),
    path('my-student-results-second/', result_views.self_student_results_secondterm, name="my-students-results-second"),
    path('my-student-results-third/', result_views.self_student_results_thirdterm, name="my-students-results-third"),


    
]
    # path('self-result/', views.SelfResultListView.as_view(), name='self-result'),
    

schoolly/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
#from django.conf.urls import url
from django.views.static import serve


# from attendance.views import AttendanceAutocomplete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('curriculum/', include('curriculum.urls', namespace='curriculum')),
    path('', include('pages.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls')),
   
    path('results/', include('results.urls', namespace='results')),
    path('students/', include('students.urls', namespace='students')),
    path('staff/', include('staff.urls', namespace='staff')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    # path('demoschool/', include('demoschool.urls', namespace='demoschool')),
    path('portal/', include('portal.urls', namespace='portal')),
    path('quizes/', include('quizes.urls', namespace = 'quizes')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('notification/', include('notification.urls', namespace = 'notification')),
    path('inventory/', include('inventory.urls', namespace = 'inventory')),
    path('quiz_results/', include('quiz_results.urls', namespace = 'quiz_results')),
    # path('demoschool/', include('demoschool.urls')),
   

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    


    

#PATH FOR DOWNLOAD URL
   #url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
   #path(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),


#    url( r'^attendance-autocomplete/$', AttendanceAutocomplete.as_view(), name='attendance-autocomplete',
#     ),

  path('djrichtextfield/', include('djrichtextfield.urls')),

# for django-rest-framework
#   path('api-auth/', include('rest_framework.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
#from wkhtmltopdf.views import PDFTemplateView
# from wkhtmltopdf import WKHtmltoPdf
from django.conf import settings
from django.conf.urls.static import static
from students import views as student_views 
from django.contrib.auth import views as auth_views
from students.views import (StudentListView,
                            StudentDetailView,
                            StudentCreateView,
                            StudentUpdateView,
                            StudentDeleteView,
                           # StudentResultUpdateView,
                            StudentCardDetailView,
                            GuardianListView,
                            MyStudentList
)

app_name = 'students'

urlpatterns = [
   
    path('', student_views.studentlist, name="student-list"),
    path('student-register', student_views.studentregisterform, name="student-registration"),
    path('student-summary', student_views.student_summary, name="student-summary"),
    # path('pdf/<pk>/', student_views.student_render_pdf_view, name="student-pdf-view"),
    # path('student-list/', StudentListView.as_view(), name="all-students"),
    path('<int:id>/', StudentDetailView.as_view(), name="students-detail"), 
    # path('<int:pk>/', StudentCardDetailView.as_view(), name='my_idcard'),
    path('new-student/', StudentCreateView.as_view(), name="students-create"),
    path('<int:id>/update/', StudentUpdateView.as_view(), name="students-update"),
    path('<int:id>/delete/', StudentDeleteView.as_view(), name="students-delete"),  

     path('guardian-list/', GuardianListView.as_view(), name="guardian-list"), 

    # path('<int:id>/result-update/', StudentResultUpdateView.as_view(), name="result-update"),

    path('pdf/<pk>/', student_views.student_render_pdf_view, name="student-pdf-view"),
    path('test-view/', student_views.render_pdf_view, name="test-view"),

    path('student-pdf', student_views.mystudent_pdf, name="student-pdf"),
    path('student-csv', student_views.mystudent_csv, name="student-csv"),

    # Search student detail app
    path('student-search/', student_views.student_search_list, name='student_search_list'),
    path('search/', student_views.search, name='search'),

    #render id card as pdf
    path('idcard-pdf/<pk>/', student_views.id_render_pdf_view, name="idcard-pdf-view"),
    #path('idcard/', PDFTemplateView.as_view(template_name='students/student_id_card.html',
    #                                       filename='id_card.pdf'), name='id-card-pdf'),

    path('api-auth/', MyStudentList.as_view(), name="apiview"),

]

students/models.py
from django.db import models
from django.shortcuts import render
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from curriculum.models import Standard, ClassGroup
from django.urls import reverse
from staff.models import StaffProfile

class Badge(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    description = models.CharField(max_length=120, blank=True)
    slug = models.SlugField(null=True, blank=True)
    
    def __str__ (self):
        return f'{self.name}'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class StudentDetail(models.Model):
    student_username = models.CharField(max_length=20, unique=True, verbose_name='Student ID', help_text='Type New Username For Student')
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Student Username', help_text='Click The Search Button To Select The New Username If Not Available, ADD New User')
    first_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=20)
    dob = models.DateField(blank=True, null=True, verbose_name='Date of Birth(Y-M-D)', default='2020-01-01')

    female = 'female'
    male = 'male'
    select_gender = 'select_gender'
    
    gender_type = [
        ('female', female),
        ('male', male),
        ('select_gender', select_gender),
    ]

    gender= models.CharField(max_length=20, choices=gender_type, default= select_gender) 
    current_class = models.ForeignKey(Standard, on_delete=models.CASCADE, blank=True, null=True)
    class_group = models.ForeignKey(ClassGroup, on_delete=models.CASCADE, blank=True, null=True)
    class_teacher = models.ForeignKey(StaffProfile, on_delete=models.CASCADE, blank=True, null=True)
    badge =  models.ForeignKey(Badge, on_delete=models.CASCADE, blank=True, null=True, default='not a prefect', verbose_name='Prefect Tittle (if is prefect)')

    day_student = 'day_student'
    boarder = 'boarder'

    student_types = [
        (day_student, 'day_student'),
        (boarder, 'boarder'),

    ]

    student_type = models.CharField(max_length=15, choices=student_types, default=day_student)
    phone = models.CharField(max_length=15, blank=True) 
    address = models.CharField(max_length=120, blank=True)

    select = 'Select'
    southwest = 'SouthWest'
    southeast = 'SouthEast'
    southsouth = 'SouthSouth'
    northwest = 'NorthWest'
    northeast = 'NorthEast'
    northcentral = 'NorthCentral'
    
    region_origin = [
        ('Select', select),
        ('SouthWest', southwest),
        ('SouthEast', southeast),
        ('SouthSouth', southsouth),
        ('NorthWest', northwest),
        ('NorthEast', northeast),
        ('NorthCentral', northcentral),
    ]

    region_origin = models.CharField(max_length=20, choices=region_origin, default=select)

    date_admitted = models.DateField(default='2020-01-01')
    class_on_admission = models.ForeignKey(Standard, on_delete=models.CASCADE, related_name='studentdetails', verbose_name='class_on_admission') 
    
    # Guardian details here..
    guardian_name = models.CharField(max_length=60, blank=False)  
    guardian_address = models.TextField(max_length=120, blank=True)  
    guardian_phone = models.CharField(max_length=15, blank=True)
    guardian_email = models.CharField(max_length=30, blank=True)

    select = 'select'
    father = 'father'
    mother = 'mother'
    sister = 'sister'
    brother = 'brother'
    aunt = 'aunt'
    uncle = 'uncle'
    other = 'other'
    

    relationship = [
        (select, 'select'),
        (father, 'father'),
        (mother, 'mother'),
        (sister, 'sister'),
        (brother, 'brother'),
        (aunt, 'aunt'),
        (uncle, 'uncle'),
        (other, 'other'), 
         

    ]

    relationship = models.CharField(max_length=25, choices=relationship, default=select, help_text="Guardian's Relationship With Student")
    
    active = 'active'
    inactive = 'inactive'
    graduated = 'graduated'
    dropped = 'dropped'
    expelled = 'expelled'
    suspended = 'suspended'

    student_status = [
        (active, 'active'),
        (inactive, 'inactive'),
        (graduated, 'graduated'),
        (dropped, 'dropped'),
        (expelled, 'expelled'),
        (suspended, 'suspended'),

    ]

    student_status = models.CharField(max_length=15, choices=student_status, default=inactive)

    class Meta:
        ordering = ['user']

    def __str__(self):
        return f'{self.last_name } - {self.first_name} ({self.user.username}) {self.current_class}'
    
    def get_absolute_url(self):
        return reverse('students:students-detail', kwargs={'id':self.id})
    
    # def save(self, *args, **kwargs):
    #     if self.student_username == "":
    #         student_username=self.user
    #         self.student_username = student_username
    #         super().save(*args, **kwargs)

students/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import StudentDetail



class StudentUpdateForm(forms.ModelForm):

    class Meta:
        model = StudentDetail
        fields = '__all__'
        # exclude = ('user',)
        widgets = {
            'date_admitted': forms.DateInput(
                format=('%d/%m/%Y'),
                attrs={'class': 'form-control', 
                       'placeholder': 'Select a date',
                       'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                      }),
            'dob': forms.DateInput(
                format=('%d/%m/%Y'),
                attrs={'class': 'form-control', 
                       'placeholder': 'Select a date',
                       'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                      }),
        }

    

class StudentRegisterForm(forms.ModelForm):

    class Meta:
        model = StudentDetail
        fields = [ 'current_class', 'class_group', 'date_admitted', 'student_type', 'class_teacher', 'class_on_admission', 'badge']
      
        widgets = {
            'date_admitted': forms.DateInput(
                format=('%d/%m/%Y'),
                attrs={'class': 'form-control', 
                       'placeholder': 'Select a date',
                       'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                      }),

            'dob': forms.DateInput(
                format=('%d/%m/%Y'),
                attrs={'class': 'form-control', 
                       'placeholder': 'Select a date',
                       'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                      }),
        }
 

students/templates/students/guardian_list.html
<h1>hello</h1>
{% for g in guardian %}
{{ g.student_username}} {{g.first_name}}- {{g.last_name}} -{{g.current_class}}  - {{g.guardian_phone}} - {{ g.guardian_email }} {{g.guardian_address}} - {{g.relationship}} {{g.student_status}}<br />
{% endfor%}

students/templates/students/search.html
<html>
<head>
   <title>Search Result</title>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
   
    {% if user.is_authenticated and user.is_superuser or user.profile.user_type == 'admin' or user.profile.user_type == 'teacher' %}
<br/></br/>
<div class="container">
   <div class="col-md-8 offset-md-2">
{% if query %}
           <h5>
           {% with results.count as total_results %}
           Found {{ total_results }} result{{ total_results|pluralize }}
           {% endwith %}
           </h5>
   {% for c in results %}
  <a href="{{c.get_absolute_url}}"><h6>{{c.last_name}} {{c.first_name}} </h6></a>
 
  <p> <span style="color:rgba(43, 43, 207, 0.753)">Current Class : </span> <strong>{{ c.current_class }} </strong><span style="color:rgba(43, 43, 207, 0.753)"> Class Teacher :</span> <strong>{{ c.class_teacher }} </strong></span></p>
  

   {% empty %}
   <h3>No results found.</h3>
   {% endfor %}
  {% endif %}
        <form action="{% url 'students:student_search_list' %}" class="form-inline" method="get">
        <button type="submit" class="btn btn-primary btn-sm mb-2">Back</button>
        </form>
    </div>
</div>
{% endif %}

</body>

<html>

students/templates/students/search_student_list.html
<html>
<head>
    <title>Student Search List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>

<body>
  
    {% if user.is_authenticated and user.is_superuser or user.profile.user_type == 'admin' or user.profile.user_type == 'teacher' %}
    <div class="container"><h1></h1></div>
<div class="container">
    <div class="card">
        <div class="card-header">
          <span><strong>Search Students </strong></span>- Use the search form to filter for students by : <em>first name, last name, teacher's name or current class.</em>
        </div>
        <div class="card-body">
 
    <form action="{% url 'students:search' %}" class="form-inline" method="get">
       <div class="form-group mb-8">
       
            <h5>{% if first_name %}{{ standard.name }}{% else %} List Of All Students {% endif %}</h5>
       </div>
       <div class="form-group mx-sm-3 mb-2">
        <label for="" class="sr-only">search</label>
        <input name="search" type="" class="form-control" id="" placeholder="Keyword">
        </div>
        <button type="submit" class="btn btn-success btn-md mb-2">Search</button>
   </form>
   </div>
   <div class="card-body"  style="padding-top:1px;">
    {% for x in student %}
    <h6> <a href="{{ x.get_absolute_url }}"> {{x.first_name}}  {{x.middle_name}}  {{x.last_name}}</a></h6>
    <p class="">Guardian Name :<strong> {{x.guardian_name}} </strong>  - Guardian Phone : <strong>{{x.guardian_phone}}</strong> </br>
      Current Class:  <strong>{{x.current_class}} </strong>  -  <span>Class Teacher:  <strong>{{ x.class_teacher.first_name}} {{ x.class_teacher.last_name}}</strong></span></p>
     <hr>
    {% endfor %}
    </div>
<!-- Page Paginator start -->
<div class="card-body">
        {% if student.has_other_pages %}
        {% if student.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page={{ studentlist.previous_page_number }}">&laquo;</a>
        {% else %}
        <a class="btn btn-outline-info mb-4" href="">&raquo;</a>

        {% endif %}
        {% for i in student.paginator.page_range %}
        {% if student.number == i %}

        <a class="btn btn-info mb-4" href="">{{ i }}</a>
        {% else %}
        <a class="btn btn-outline-info mb-4" href="?page={{ i }}">{{ i }}</a>
        {% endif %}
        {% endfor %}
        {% if student.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ studentlist.next_page_number }}">&raquo;</a>
        {% else %}

        <a class="btn btn-outline-info mb-4" href="">&raquo;</a>
        {% endif %}
      										
        {% endif %}
    </div>
        <!-- Page Paginator end -->


</div>
</div>
{% endif %}

</body>

</html>

students/templates/students/student_list.html
{% extends 'portal/portal-home.html'%}
{% load crispy_forms_tags %}
{% load static %}

{% block title %} <title> Student List</title>{% endblock title %}

{% block content_body %}
{% if user.is_authenticated and user.is_superuser or user.profile.user_type == 'admin' or user.profile.user_type == 'teacher' %}

		<div class="content-body">
			<!-- row -->
			<div class="container-fluid">
				<div class="d-flex justify-content-between align-items-center flex-wrap">
					<div class="card-action coin-tabs mb-2">
						
						<ul class="nav nav-tabs" role="tablist">
							<!-- <li class="nav-item">
								<a class="nav-link"href="{% url 'students:student-pdf' %}">View PDF</a>
							</li> -->
							<!-- <li class="nav-item">
								<a class="nav-link" href="{% url 'students:student-csv' %}">Download CSV File</a>
							</li> -->
							<li><div>                 
								{% if messages %}
								{% for message in messages %}
								<div class ="alert alert-{{ message.tags }}">{{ message }}</div>
								{% endfor%}
								{% endif%}
							 </div></li>
		
						</ul>
					</div>
					<div>
					<form action="" method="get">
											
						<!-- {{ StudentFilter.form|crispy}} -->
						{{ studentdetail_filter.form }}
						
						<button class="btn btn-primary" type="submit">Search </button>
					</form>	</div>

					<div class="d-flex align-items-center mb-2 flex-wrap"> 
						<div class="guest-calendar">
							<div id="reportrange" class="pull-right reportrange" style="width: 100%">
								<span>Students List</span><b class="caret"></b>
								<i class="fas fa-user ms-3"></i>
								<button class="btn btn-primary"><a href="{% url 'students:student_search_list' %}" style="color:azure;">Search For Student </a></button> ---
								<button class="btn btn-primary"><a href="{% url 'students:student-csv' %}" style="color:azure;">DOWNLOAD TO EXCEL </a></button>

							</div>
						</div>
						<div class="newest ms-3">
							<!-- <select class="default-select"> -->
								<!-- <option><a href="https://google.com">Teacher's List</a></option> -->
								
							</select>
						</div>	
					</div>
				</div>
<!-- 			
						<!-- USING FILTER TO GET INFORMATION -->
							<div class="row">
								<div ">	
									<div>
										<!-- <div style="float:left; padding:4px; width:30%;"> -->
											<!-- <div> -->
												<!-- <form action="" method="get"> -->
											
												<!-- {{ StudentFilter.form|crispy}} -->
												<!-- {{ studentdetail_filter.form }} -->
												
												<!-- <button class="btn btn-primary" type="submit">Search </button> -->
											<!-- </form>	</div> -->
										</div>
									
									  </div>		

									  <!-- END USING FILTER TO GET INFORMATION -->
													
								</div>
								</div>
							
								<div class="col-xl-12">
									<div class="card">
										
										<div class="card-body p-0">
											<div class="tab-content">	
									<div class="tab-pane active show" id="AllGuest">
										<div class="table-responsive">
											<table class="table card-table display mb-4 shadow-hover default-table table-responsive-lg" id="guestTable-all">
												<thead>
													<tr>
														<th class="bg-none">
															<div class="form-check style-1">
															  <input class="form-check-input" type="checkbox" value="" id="checkAll">
															</div>
														</th>
														
														<th>Student ID</th>
														<th>Admin Date</th>
														<th>Current Class</th>
														<th>Teacher ID</th>
														<th>Parent's Phone</th>
														<th>Status</th>
																											
													</tr>
												</thead>
												<tbody>
													{% for student in studentlist %}
							
													<tr>
												
														<td>
															<div class="form-check style-1">
															  <input class="form-check-input" type="checkbox" value="">
															</div>
														</td>
														<td>
															<div class="concierge-bx d-flex align-items-center">
																<img class="me-3 rounded" src="{{student.user.profile.image.url}}" alt="">
																<div>
																	<h5 class="fs-16 mb-0 text-nowrap">
																	<a class="text-black" href="{% url 'students:students-detail' student.pk %}">{{ student.user.username}}- <span style="font-size:9px;, color:grey;">{{student.student_username}}</span></h5>
																	<span class="text-primary fs-14">{{ student.first_name}} {{ student.last_name}}</span></a>
																</div>
															</div>
														</td>
														<td class="text-nowrap">
															<span>{{ student.date_admitted}}</span>
														</td>
														<td class="text-nowrap">
															
																<span>{{ student.current_class}}</span>	
																<span></span>										
														</td>
														<td class="text-nowrap">
															<span>{{ student.class_teacher.user.username }}</span>
																<span></span>
														</td>
														<td class="text-nowrap">
														<span>{{ student.guardian_phone }}</span>
															<span></span>
														</div>
														
														</td>
														
														<td>
															<div>
																{% if student.student_status == 'active' %}
																<span style="color:green"><b>Active</b></span>		
															
																{% elif student.student_status == 'dropped' %}
																<span style="color:red"><b>Dropped</b></span>	
																{% elif student.student_status == 'graduated' %}
																<span style="color:green"><b>Graduated</b></span>	
																{% elif student.student_status == 'expelled' %}
																<span style="color:grey"><b>Expelled</b></span>	
															</div>
																											
															{% endif %}
														</td>	

														{% endfor %}
													</tr>	
												</tbody>
											</table>
										
											<!-- Page Paginator start -->
											{% if studentlist.has_other_pages %}
											{% if studentlist.has_previous %}
											<a class="btn btn-outline-info mb-4" href="?page={{ studentlist.previous_page_number }}">&laquo;</a>
											{% else %}
											<a class="btn btn-outline-info mb-4" href="">&raquo;</a>
	
											{% endif %}
											{% for i in studentlist.paginator.page_range %}
											{% if studentlist.number == i %}
	
											<a class="btn btn-info mb-4" href="">{{ i }}</a>
											{% else %}
											<a class="btn btn-outline-info mb-4" href="?page={{ i }}">{{ i }}</a>
											{% endif %}
											{% endfor %}
											{% if studentlist.has_next %}
											<a class="btn btn-outline-info mb-4" href="?page={{ studentlist.next_page_number }}">&raquo;</a>
											{% else %}
											
											<a class="btn btn-outline-info mb-4" href="">&raquo;</a>
											{% endif %}
										
										{% endif %}
										<!-- Page Paginator end -->

										</div>	
									</div>	
									
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		{% endif %}
		<!-- ***********************************--> -->

		{% endblock content_body %}
		<!--**********************************-->
			
			{% block scripts %}

			<script src="{% static 'portal/vendor/moment/moment.min.js' %}"></script>
    		<script src="{% static 'portal/vendor/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
			<script src="{% static 'portal/vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
			<script src="{% static 'portal/js/plugins-init/datatables.init.js' %}"></script>
	
			<script src="{% static 'portal/vendor/global/global.min.js' %}"></script>
			<script src="{% static 'portal/vendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>
			
			<!-- Apex Chart -->
				<script src="{% static 'portal/vendor/apexchart/apexchart.js' %}"></script>
			
			<!-- Chart piety plugin files -->
			
				<!-- Dashboard 1 -->
			<script src="{% static 'portal/js/dashboard/dashboard-1.js' %}"></script>
			
			<script src="{% static 'portal/vendor/owl-carousel/owl.carousel.js' %}"></script>
			<script src="{% static 'portal/vendor/bootstrap-datetimepicker/js/moment.js' %}"></script>
			<script src="{% static 'portal/vendor/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
			
			<script src="{% static 'portal/js/custom.min.js' %}"></script>
			<script src="{% static 'portal/js/dlabnav-init.js' %}"></script>
			<script src="{% static 'portal/js/demo.js' %}"></script>
			<script src="{% static 'portal/js/styleSwitcher.js' %}"></script>

			{% endblock scripts %}