attendance/urls.py
from django.urls import path
# from attendance import views as attendance_views
from . import views



app_name = 'attendance'

urlpatterns = [
    
    # path('attendance-form/', attendance_views.student_attendance, name='attendance_form'),
    # path('my-std-att-form/', attendance_views.my_student_att_form, name='my-std-att-form'),
    # path('attendance-view/', attendance_views.attendance_view, name='attendance_view'),

    # # path('pdf/<pk>/', attendance_views.attendance_render_pdf_view, name="attendance-pdf-view"),

    # # path('attendance-pdf', attendance_views.attendance_pdf, name="attendance-pdf"),
    # path('attendance-csv', attendance_views.attendance_csv, name="attendance-csv"),


    path('teacher/', views.index, name='index'),
    path('student/', views.index2, name='index2'),
    path('student/<slug:stud_id>/attendance/', views.attendance, name='attendance'),
    path('student/<slug:stud_id>/<slug:course_id>/attendance/', views.attendance_detail, name='attendance_detail'),
    path('student/<slug:class_id>/timetable/', views.timetable, name='timetable'),
    # path('student/<slug:class_id>/search/', views.student_search, name='student_search'),

    path('student/<slug:stud_id>/marks_list/', views.marks_list, name='marks_list'),

    path('teacher/<slug:teacher_id>/<int:choice>/Classes/', views.t_clas, name='t_clas'),
    path('teacher/<int:assign_id>/Students/attendance/', views.t_student, name='t_student'),
    path('teacher/<int:assign_id>/ClassDates/', views.t_class_date, name='t_class_date'),
    path('teacher/<int:ass_c_id>/Cancel/', views.cancel_class, name='cancel_class'),
    path('teacher/<int:ass_c_id>/attendance/', views.t_attendance, name='t_attendance'),
    path('teacher/<int:ass_c_id>/Edit_att/', views.edit_att, name='edit_att'),
    path('teacher/<int:ass_c_id>/attendance/confirm/', views.confirm, name='confirm'),
    path('teacher/<slug:stud_id>/<slug:course_id>/attendance/', views.t_attendance_detail, name='t_attendance_detail'),
    path('teacher/<int:att_id>/change_attendance/', views.change_att, name='change_att'),
    path('teacher/<int:assign_id>/Extra_class/', views.t_extra_class, name='t_extra_class'),
    path('teacher/<slug:assign_id>/Extra_class/confirm/', views.e_confirm, name='e_confirm'),
    path('teacher/<int:assign_id>/Report/', views.t_report, name='t_report'),

    path('teacher/<slug:teacher_id>/t_timetable/', views.t_timetable, name='t_timetable'),
    path('teacher/<int:asst_id>/Free_teachers/', views.free_teachers, name='free_teachers'),

    path('teacher/<int:assign_id>/marks_list/', views.t_marks_list, name='t_marks_list'),
    path('teacher/<int:assign_id>/Students/Marks/', views.student_marks, name='t_student_marks'),
    path('teacher/<int:marks_c_id>/marks_entry/', views.t_marks_entry, name='t_marks_entry'),
    path('teacher/<int:marks_c_id>/marks_entry/confirm/', views.marks_confirm, name='marks_confirm'),
    path('teacher/<int:marks_c_id>/Edit_marks/', views.edit_marks, name='edit_marks'),

]

    # Attendance App

blog/urls.py
from django.urls import path
from .views import (
    PostDetailView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
   
    
)
from blog import views as blog_views


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog_home'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('like/<int:pk>', blog_views.LikeView, name='like_post'),
    
]

schoolly/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
#from django.conf.urls import url
from django.views.static import serve


# from attendance.views import AttendanceAutocomplete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('curriculum/', include('curriculum.urls', namespace='curriculum')),
    path('', include('pages.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls')),
   
    path('results/', include('results.urls', namespace='results')),
    path('students/', include('students.urls', namespace='students')),
    path('staff/', include('staff.urls', namespace='staff')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    # path('demoschool/', include('demoschool.urls', namespace='demoschool')),
    path('portal/', include('portal.urls', namespace='portal')),
    path('quizes/', include('quizes.urls', namespace = 'quizes')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('notification/', include('notification.urls', namespace = 'notification')),
    path('inventory/', include('inventory.urls', namespace = 'inventory')),
    path('quiz_results/', include('quiz_results.urls', namespace = 'quiz_results')),
    # path('demoschool/', include('demoschool.urls')),
   

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    


    

#PATH FOR DOWNLOAD URL
   #url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
   #path(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),


#    url( r'^attendance-autocomplete/$', AttendanceAutocomplete.as_view(), name='attendance-autocomplete',
#     ),

  path('djrichtextfield/', include('djrichtextfield.urls')),

# for django-rest-framework
#   path('api-auth/', include('rest_framework.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from curriculum.models import Standard, Session
from students.models import StudentDetail
from staff.models import StaffProfile, Department

import math
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, post_delete
from datetime import timedelta



class Attendance_1(models.Model):
    student_id = models.ForeignKey(StudentDetail, on_delete=models.CASCADE, blank=True, null=True)
    # standard = models.ForeignKey(Standard, on_delete=models.CASCADE, blank=True, null=True)
    session = models.ForeignKey(Session, on_delete=models.CASCADE, blank=True, null=True, default='2023/2024')
    attendance_date = models.DateField(null=True)
    morning_status = models.BooleanField(default=False)
    afternoon_status = models.BooleanField(default=False)
    authorized_sign = models.CharField(max_length=20, default='none')
    date_taken = models.DateTimeField(auto_now_add=True)
        
    class Meta:
        unique_together = ['student_id', 'attendance_date', 'session',]
    
    def __str__ (self):
        return f'{self.student_id}'





sex_choice = (
    ('Male', 'Male'),
    ('Female', 'Female')
)

time_slots = (
    ('7:30 - 8:30', '7:30 - 8:30'),
    ('8:30 - 9:30', '8:30 - 9:30'),
    ('9:30 - 10:30', '9:30 - 10:30'),
    ('11:00 - 11:50', '11:00 - 11:50'),
    ('11:50 - 12:40', '11:50 - 12:40'),
    ('12:40 - 1:30', '12:40 - 1:30'),
    ('2:30 - 3:30', '2:30 - 3:30'),
    ('3:30 - 4:30', '3:30 - 4:30'),
    ('4:30 - 5:30', '4:30 - 5:30'),
)

DAYS_OF_WEEK = (
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
)

test_name = (
    ('Internal test 1', 'Internal test 1'),
    ('Internal test 2', 'Internal test 2'),
    ('Internal test 3', 'Internal test 3'),
    ('Event 1', 'Event 1'),
    ('Event 2', 'Event 2'),
    ('Semester End Exam', 'Semester End Exam'),
)



class Dept(models.Model):
    id = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Course(models.Model):
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    id = models.CharField(primary_key='True', max_length=50)
    name = models.CharField(max_length=50)
    shortname = models.CharField(max_length=50, default='X')

    def __str__(self):
        return self.name

class Class(models.Model):
    # courses = models.ManyToManyField(Course, default=1)
    id = models.CharField(primary_key='True', max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    # section = models.CharField(max_length=100)
    section = models.ForeignKey(Session, on_delete=models.CASCADE, verbose_name='Session')
    sem = models.IntegerField(verbose_name='Term', help_text='Enter 1 for 1stTerm, 2 for 2ndTerm & 3 for 3rdTerm')

    class Meta:
        verbose_name_plural = 'classes'

    def __str__(self):
        d = Dept.objects.get(name=self.dept)
        return '%s : %d %s  ' % (self.section, self.sem, d.name )

class Student(models.Model):
    student_id = models.OneToOneField(StudentDetail, on_delete=models.CASCADE, null=True, verbose_name='Student Detail')
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, verbose_name='Student Username')
    USN = models.CharField(primary_key='True', max_length=100, verbose_name= 'Repeat Std. Username')
    name = models.CharField(max_length=200, verbose_name='Full Name')
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE, default=1)
    current_class = models.OneToOneField(Standard, on_delete=models.CASCADE, null=True, blank=True)
    
    
    # DOB = models.DateField(default='1998-01-01', null=True, blank=True)

    def __str__(self):
        return self.name
        # return f' {self.name} - {self.student_id}'
    


class Teacher(models.Model):
    staff_profile = models.OneToOneField(StaffProfile, on_delete=models.CASCADE, null=True, verbose_name= "Teacher's Detail",  help_text='Select Teacher Detail From List')
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, verbose_name= 'Teacher Username',  help_text='Click Search Button To Select Same As Above')
    id = models.CharField(primary_key=True, max_length=100, verbose_name= 'Enter Username Again',  help_text='Type The Username Again Correctyl here')
    name = models.CharField(max_length=100, verbose_name='Full Name',  help_text='Enter Teacher Full Name')
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE, default=1, verbose_name='Class-In-Charge',  help_text='Select Class-In-Charge From List')
    
    # DOB = models.DateField(default='1980-01-01')

    def __str__(self):
        return self.name
    

class Assign(models.Model):
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('course', 'class_id', 'teacher'),)

    def __str__(self):
        cl = Class.objects.get(id=self.class_id_id)
        cr = Course.objects.get(id=self.course_id)
        te = Teacher.objects.get(id=self.teacher_id)
        return '%s : %s : %s' % (te.name, cr.shortname, cl)
    
class AssignTime(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    period = models.CharField(max_length=50, choices=time_slots, default='11:00 - 11:50')
    day = models.CharField(max_length=15, choices=DAYS_OF_WEEK)


class AttendanceClass(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    date = models.DateField()
    status = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Attendance'
        verbose_name_plural = 'Attendance'

class Attendance(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    attendanceclass = models.ForeignKey(AttendanceClass, on_delete=models.CASCADE, default=1)
    date = models.DateField(default='2018-10-23')
    status = models.BooleanField(default='True')

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.name, cname.shortname)
    

class AttendanceTotal(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)

    @property
    def att_class(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        return att_class

    @property
    def total_class(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        return total_class

    @property
    def attendance(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        if total_class == 0:
            attendance = 0
        else:
            attendance = round(att_class / total_class * 100, 2)
        return attendance

    @property
    def classes_to_attend(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        cta = math.ceil((0.75 * total_class - att_class) / 0.25)
        if cta < 0:
            return 0
        return cta

class StudentCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)
        verbose_name_plural = 'Marks'

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.name, cname.shortname)

    def get_cie(self):
        marks_list = self.marks_set.all()
        m = []
        for mk in marks_list:
            m.append(mk.marks1)
        cie = math.ceil(sum(m[:5]) / 2)
        return cie

    def get_attendance(self):
        a = AttendanceTotal.objects.get(student=self.student, course=self.course)
        return a.attendance

class Marks(models.Model):
    studentcourse = models.ForeignKey(StudentCourse, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, choices=test_name, default='Internal test 1')
    marks1 = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    class Meta:
        unique_together = (('studentcourse', 'name'),)

    @property
    def total_marks(self):
        if self.name == 'Semester End Exam':
            return 100
        return 20
    

class MarksClass(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, choices=test_name, default='Internal test 1')
    status = models.BooleanField(default='False')

    class Meta:
        unique_together = (('assign', 'name'),)

    @property
    def total_marks(self):

attendance/forms.py
# from django import forms
# from attendance.models import Attendance
# from students.models import StudentDetail


# # class StudentAttendanceForm(forms.ModelForm):
    
# #     class Meta:
# #         model = Attendance
# #         fields = ['student_id', 'session', 'attendance_date', 'morning_status', 'afternoon_status', 'authorized_sign']
# #         widgets = {
# #             'attendance_date': forms.DateInput(
# #                 format=('%d/%m/%Y'),
# #                 attrs={'class': 'form-control', 
# #                        'placeholder': 'Select a date',
# #                        'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
# #                       }),
# #         }

# # class MyStudentAttendanceForm(forms.ModelForm):
    
# #     # def __init__(self, *args, **kwargs):
# #     #     super().__init__(*args, **kwargs)
# #     #     self.fields['student_id'].queryset = StudentDetail.objects.filter(class_teacher__user=request.user).order_by('student_username')
# #     #     # self.fields['student_id'].queryset = Attendance.objects.filter(student_id__class_teacher__user=request.user)
    
# #     class Meta:
# #         model = Attendance
# #         def __init__(self, *args, **kwargs):
# #             student_id = kwargs.pop('student_id', None)
# #             super(MyStudentAttendanceForm, self).__init__(*args, **kwargs)
        
# #         fields = '__all__'
# #         widgets = {
# #             'attendance_date': forms.DateInput(
# #                 format=('%d/%m/%Y'),
# #                 attrs={'class': 'form-control', 
# #                        'placeholder': 'Select a date',
# #                        'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
# #                       }),
# #         }



   

attendance/templates/attendance/att_detail.html
{% extends 'attendance/base.html' %}

    {% block content %}
        <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-table"></i>
            <strong>{{ cr.name }}</strong></div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                        <th>#</th>
                        <th>Date</th>
                        <th>Day</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                  </thead>
                  <tbody>
                        {% for a in att_list %}
                        <tr class="row100 body">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ a.date }}</td>
                            <td>{{ a.date|date:"l" }}</td>
                            {% if a.status %}
                            <td class="p-3 mb-2 bg-success text-white">Present <span class="glyphicon glyphicon-thumbs-up"></span></td>
                            {% else %}
                            <td class="p-3 mb-2 bg-danger text-white">Absent <span class="glyphicon glyphicon-thumbs-down"></span</td>
                            {% endif %}
                        </tr>
                    {% empty %}
                            <p>student has no attendance</p>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
            </div>
          </div>


    {% endblock %}

attendance/templates/attendance/homepage.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Attendance Page</title>
      {% load static %}

    <!-- Bootstrap core CSS -->
      <link href="{% static '/attendance/homepage/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Custom styles for this template -->
      <link href="{% static '/attendance/homepage/css/heroic-features.css' %}" rel="stylesheet">
          <link href="{% static '/attendance/bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">



  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
          <a class="navbar-brand" href="{% url 'attendance:index2' %}">SchoollyEdtech Attendance </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link text-capitalize">{{ request.user.student.name }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <!-- Jumbotron Header -->
      <header class="jumbotron my-4">
        <h1 class="display-3 text-capitalize">Welcome {{ request.user.student.name }}</h1>
{#        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>#}
{#        <a href="#" class="btn btn-primary btn-lg">Call to action!</a>#}
      </header>

      <!-- Page Features -->
      <div class="row text-center">

        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
              <a href="{% url 'attendance:attendance' request.user.student.USN %}">
                <img class="card-img-top" src="{% static 'attendance/images/attendance2.jpg' %}" alt="">
              </a>
              <div class="card-body">
              <h4 class="card-title">Attendance</h4>
              <p class="card-text">View the attendance status for each of your courses. The attendance of each course is
                  also displayed as list of classes that were conducted.</p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" role="button" href="{% url 'attendance:attendance' request.user.student.USN %}"> View Attendance</a>
            </div>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
              <a href="{% url 'attendance:marks_list' request.user.student.USN %}">
                <img class="card-img-top" src="{% static 'attendance/images/marks.jpg' %}" alt="">
              </a>
              <div class="card-body">
              <h4 class="card-title">Marks</h4>
              <p class="card-text">View the marks obtained for each of your courses. These include the marks of 3
                  internal assessment, 2 events and the Semester End Exam  </p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" role="button" href="{% url 'attendance:marks_list' request.user.student.USN %}">View Marks</a>
            </div>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
              <a href="{% url 'attendance:timetable' request.user.student.class_id_id %}">
                <img class="card-img-top" src="{% static 'attendance/images/timetable.png' %}" alt="">
              </a>
              <div class="card-body">
              <h4 class="card-title">TimeTable</h4>
              <p class="card-text">View the timetable in a tabular form. The timetable displays all the courses of the
                  student and the time and day at which they are conducted.</p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" role="button" href="{% url 'attendance:timetable' request.user.student.class_id_id %}">View TimeTable</a>
            </div>
          </div>
        </div>


      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="/users/logout">Logout</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript -->


      <script src="{% static '/info/homepage/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/info/homepage/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

attendance/templates/attendance/t_class_date.html
{% extends 'attendance/base.html' %}

{% block content %}
    <div class="card mb-3">
        <div class="card-header">
              <i class="fas fa-table"></i>
            <b>Attendance</b></div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                        <th>Date</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for a in att_list %}
                    <tr>
                        <td>{{ a.date }}</td>
                        {% if a.status == 0 %}
                            <td class="p-3 mb-2 bg-danger text-white">Not Marked</td>
                            <td>
                                <a class="btn btn-primary" href="{% url 'attendance:t_attendance' a.id %}" role="button">Enter Attendance</a>
                                <a class="btn btn-warning" href="{% url 'attendance:cancel_class' a.id %}">Cancel Class</>
                            </td>

                        {% elif a.status == 1 %}
                            <td class="p-3 mb-2 bg-success text-white">Marked</td>
                            <td><a class="btn btn-secondary" href="{% url 'attendance:edit_att' a.id %}" role="button">Edit Attendance</a> </td>

                        {% else %}
                            <td class="p-3 mb-2 bg-warning text-white">Cancelled</td>
                            <td><a class="btn btn-primary" href="{% url 'attendance:t_attendance' a.id %}" role="button">Enter Attendance</a></td>
                        {% endif %}
                    </tr>
                    {% empty %}
                            <p>student has no courses</p>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
        </div>
    </div>
{% endblock %}

attendance/templates/attendance/t_extra_class.html
{% extends 'attendance/base.html' %}
{% block content %}
{% if c.student_set.all %}

<form action="{% url 'attendance:e_confirm' ass.id %}" method="post">
    {% csrf_token %}
    <label for="date">Enter Date: </label>
    <input type="date" name="date">


    <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
         <b>{{ dept1.name }}</b></div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                    <th>Student name</th>
                    <th></th>
                </tr>
              </thead>
                <tbody>
                {% for s in c.student_set.all %}
                    <tr>
                    <td>{{s.name}}</td>
                    <td>
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">

                                <label class="btn btn-outline-success active">
                                    <input type="radio" name="{{ s.USN }}" id="option1" autocomplete="off" value="present" checked> Present
                                </label>

                                <label class="btn btn-outline-danger">
                                    <input type="radio" name="{{ s.USN }}" id="option2" autocomplete="off" value="absent"> Absent
                                </label>
                        </div>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
      </div>


    <input class="btn btn-success" type="submit" value="Submit">
</form>


{% else %}
    <p>No students in Class</p>
{% endif %}

{% endblock %}