blog/urls.py
from django.urls import path
from .views import (
    PostDetailView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
   
    
)
from blog import views as blog_views


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog_home'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('like/<int:pk>', blog_views.LikeView, name='like_post'),
    
]

portal/urls.py
from django.urls import path
from portal import views as portal_views 
from . import views


app_name = 'portal'

urlpatterns = [
    path('home/', portal_views.portal_home, name="portal-home"),
    path('register-class/', portal_views.register_new_standard, name="register-class"),
    path('register-class-section/', portal_views.register_new_classgroup, name="register-classgroup"),
    path('register-new-session/', portal_views.register_new_session, name="register-session"),
    path('register-new-category/', portal_views.register_new_category, name="register-category"),
    path('register-new-department/', portal_views.register_new_department, name="register-department"),
    path('register-new-subject/', portal_views.register_exam_subjects, name="register-subject"),
    path('register-exam/', portal_views.register_exam, name="register-exam"),
    path('<int:pk>/', views.StudentCardDetailView.as_view(), name='my_idcard'),

    path('category-list/', views.CategoryListView.as_view(), name="category_list"),
    path('department-list/', views.DepartmentListView.as_view(), name="department_list"),
    path('subjects-list/', views.SubjectListView.as_view(), name="subject_list"),
    path('exam-list/', views.ExamListView.as_view(), name="exam_list"),
    path('session-list/', views.SessionListView.as_view(), name="session_list"),
    path('class-group-list/', views.ClassGroupListView.as_view(), name="classgroup_list"),
    path('exam/', portal_views.set_exam, name='set-exam'), 
   


]

schoolly/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
#from django.conf.urls import url
from django.views.static import serve


# from attendance.views import AttendanceAutocomplete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('curriculum/', include('curriculum.urls', namespace='curriculum')),
    path('', include('pages.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls')),
   
    path('results/', include('results.urls', namespace='results')),
    path('students/', include('students.urls', namespace='students')),
    path('staff/', include('staff.urls', namespace='staff')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    # path('demoschool/', include('demoschool.urls', namespace='demoschool')),
    path('portal/', include('portal.urls', namespace='portal')),
    path('quizes/', include('quizes.urls', namespace = 'quizes')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('notification/', include('notification.urls', namespace = 'notification')),
    path('inventory/', include('inventory.urls', namespace = 'inventory')),
    path('quiz_results/', include('quiz_results.urls', namespace = 'quiz_results')),
    # path('demoschool/', include('demoschool.urls')),
   

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    


    

#PATH FOR DOWNLOAD URL
   #url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
   #path(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),


#    url( r'^attendance-autocomplete/$', AttendanceAutocomplete.as_view(), name='attendance-autocomplete',
#     ),

  path('djrichtextfield/', include('djrichtextfield.urls')),

# for django-rest-framework
#   path('api-auth/', include('rest_framework.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from django.conf.urls.static import static
from staff import views as user_views 
from django.contrib.auth import views as auth_views
from .views import StaffDetailView, StaffUpdateView, StaffDeleteView, StaffListView

app_name = 'staff'

urlpatterns = [
    path('staff-form/', user_views.staffupdateprofile, name="staff_form"),
    path('staff-create/', user_views.staffprofile, name="staff_create"),
    # path('staff-academic/', user_views.staffacademic, name="staff-academic"),
    path('staff-list/', user_views.stafflist, name="staff_list"),
    path('my-students/', user_views.self_student_list, name="my-students"),
    path('my-students-attendance/', user_views.self_student_attendance, name="my-students-attendance"),
    # path('', StaffListView.as_view(), name="staff_list"),
    path('<str:id>/', StaffDetailView.as_view(), name="staff_detail"),
    path('<int:id>/update/', StaffUpdateView.as_view(), name="staff_update"),
    path('<int:id>/delete/', StaffDeleteView.as_view(), name="staff_delete"), 
    path('staff-pdf', user_views.staff_pdf, name="staff-pdf"),
    path('staff-csv', user_views.staff_csv, name="staff-csv"),


]

students/urls.py
from django.urls import path
#from wkhtmltopdf.views import PDFTemplateView
# from wkhtmltopdf import WKHtmltoPdf
from django.conf import settings
from django.conf.urls.static import static
from students import views as student_views 
from django.contrib.auth import views as auth_views
from students.views import (StudentListView,
                            StudentDetailView,
                            StudentCreateView,
                            StudentUpdateView,
                            StudentDeleteView,
                           # StudentResultUpdateView,
                            StudentCardDetailView,
                            GuardianListView,
                            MyStudentList
)

app_name = 'students'

urlpatterns = [
   
    path('', student_views.studentlist, name="student-list"),
    path('student-register', student_views.studentregisterform, name="student-registration"),
    path('student-summary', student_views.student_summary, name="student-summary"),
    # path('pdf/<pk>/', student_views.student_render_pdf_view, name="student-pdf-view"),
    # path('student-list/', StudentListView.as_view(), name="all-students"),
    path('<int:id>/', StudentDetailView.as_view(), name="students-detail"), 
    # path('<int:pk>/', StudentCardDetailView.as_view(), name='my_idcard'),
    path('new-student/', StudentCreateView.as_view(), name="students-create"),
    path('<int:id>/update/', StudentUpdateView.as_view(), name="students-update"),
    path('<int:id>/delete/', StudentDeleteView.as_view(), name="students-delete"),  

     path('guardian-list/', GuardianListView.as_view(), name="guardian-list"), 

    # path('<int:id>/result-update/', StudentResultUpdateView.as_view(), name="result-update"),

    path('pdf/<pk>/', student_views.student_render_pdf_view, name="student-pdf-view"),
    path('test-view/', student_views.render_pdf_view, name="test-view"),

    path('student-pdf', student_views.mystudent_pdf, name="student-pdf"),
    path('student-csv', student_views.mystudent_csv, name="student-csv"),

    # Search student detail app
    path('student-search/', student_views.student_search_list, name='student_search_list'),
    path('search/', student_views.search, name='search'),

    #render id card as pdf
    path('idcard-pdf/<pk>/', student_views.id_render_pdf_view, name="idcard-pdf-view"),
    #path('idcard/', PDFTemplateView.as_view(template_name='students/student_id_card.html',
    #                                       filename='id_card.pdf'), name='id-card-pdf'),

    path('api-auth/', MyStudentList.as_view(), name="apiview"),

]

staff/views.py
from multiprocessing import context
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from staff.forms import StaffRegisterForm, StaffUpdateForm
from staff.models import StaffProfile
from students.models import StudentDetail
from results.models import ResultSheet
from curriculum.models import Standard
#from attendance.models import Attendance
from django.contrib.auth.models import User
from users.models import Profile
from users.forms import UserUpdateForm, UserRegisterForm
from attendance.models import Attendance
from django.http import HttpResponse
from django.views.generic import DetailView, UpdateView, DeleteView, ListView
from django.db.models import Count
# For Filter
from .filters import StaffFilter
from django_filters.views import FilterView
# For panigation
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
#for pdf
from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
# for csv
import csv

# Create your views here.


@login_required
def staffupdateprofile(request):
    if request.method == 'POST':
        
        aca_form = StaffRegisterForm(request.POST)
        if aca_form.is_valid():
           
            aca_form.save()
            messages.success(request, f'New Staff Registered successfully')
            return redirect('staff:staff_detail')
    else:
      
        aca_form = StaffRegisterForm

    context = {
        
        'aca_form': aca_form,
    }

    return render(request, 'staff/staff_register_form.html', context)


@login_required
def stafflist(request):
    stafflist = StaffProfile.objects.all()
    staffprofile_filter = StaffFilter(request.GET, queryset=stafflist) 
    stafflist = staffprofile_filter.qs
    
    # PAGINATOR METHOD
    page = request.GET.get('page', 1)
    paginator = Paginator(stafflist, 40)
    try:
        stafflist = paginator.page(page)
    except PageNotAnInteger:
        stafflist = paginator.page(1)
    except EmptyPage:
        stafflist = paginator.page(paginator.num_pages)

    context = {
        'stafflist' : StaffProfile.objects.all(),
        'staffprofile_filter': staffprofile_filter,
        'stafflist': stafflist,

    }
    return render (request, 'staff/staff_list.html', context)

#teachers seeing the students in their class
@login_required
def self_student_list(request):
    my_students = StudentDetail.objects.filter(class_teacher__user=request.user).order_by('student_username')

    context = {
        'my_students': my_students
       
    }

    return render (request, 'staff/my_students.html', context)



@login_required
def self_student_attendance(request):
    my_students_attendance = Attendance.objects.filter(student_id__class_teacher__user=request.user).order_by('student_id')
    att_count = Attendance.objects.values('student_id__first_name').annotate(c=Count('student_id__first_name')).order_by('-c')
    student_att = Attendance.objects.filter().order_by('student_id').values('student_id__last_name').annotate(count=Count('student_id__last_name'))
    my_own_students = StudentDetail.objects.filter(class_teacher__user=request.user).order_by('student_username')
    my_student_att = Attendance.objects.filter(student_id__class_teacher__user=request.user).order_by('student_id').values('student_id__last_name').annotate(count=Count('student_id__last_name'))

    # PAGINATOR
    page = request.GET.get('page', 1)
    paginator = Paginator(my_students_attendance, 30)
    try:
        my_students_attendance = paginator.page(page)
    except PageNotAnInteger:
        my_students_attendance = paginator.page(1)
    except EmptyPage:
        my_students_attendance = paginator.page(paginator.num_pages)


    
    context = {
        'my_students_attendance': my_students_attendance,
        'att_count' : Attendance.objects.values('student_id__first_name').annotate(c=Count('student_id__first_name')).order_by('-c'),
        'student_att' : student_att,
        'my_own_students': my_own_students,
        'my_student_att' : my_student_att

    }

    return render (request, 'staff/my_students_attendance.html', context)
    # return render (request, 'staff/att_test.html', context)




class StaffListView(LoginRequiredMixin, ListView):
    context_object_name = 'stafflist'
    model = StaffProfile
    queryset = StaffProfile.objects.all()
    template_name = 'staff/staff_list.html'
    paginate_by = 10
    # filterset_class = StaffFilter
    


# Generate a PDF staff list
def staff_pdf(request):
    # create Bytestream buffer
    buf = io.BytesIO()
    #create a canvas
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
    # create a text object
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont("Helvetica", 12)
    # Add some lines of text
    # lines = [
    #     "This is line 1",
    #     "This is line 2",
    #     "This is line31",
    #     "This is line 4",
    # ]
    # Designate the model
    staff = StaffProfile.objects.all()

    # Create a blank list
        
    lines = [" Staff List Report"]

    for staffs in staff:
        lines.append(""),
        lines.append("Username: " + staffs.user.username),
        lines.append("Qualification: " + staffs.qualification),
        # lines.append("Year: " + staffs.year),
        lines.append("Institution: " + staffs.institution),
        lines.append ("Marital_Status: " + staffs.marital_status),
        lines.append("Phone: " + staffs.phone),
        lines.append("========="),


    # loop
    for line in lines:
        textob.textLine(line)
    #fininsh up
    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)
    # Return something
    return FileResponse(buf, as_attachment=False, filename='staff.pdf')


# Generate a CSV staff list
def staff_csv(request):
    response = HttpResponse(content_type ='text/csv')
    response['Content-Disposition'] = 'attachment; filename=staff.csv'
    
# Create a csv writer
    writer = csv.writer(response)

    staff = StaffProfile.objects.all()
    
    # Add column headings to the csv files
    writer.writerow(['USERNAME', 'FIRST NAME', 'LAST NAME', 'GENDER', 'DATE EMPLOYED', 'PHONE', 'EMAIL', 'QUALIFICATION', 'CLASS-IN-CHARGE'])


    # Loop thru and output
    for staffs in staff:
        writer.writerow([staffs.user.username, staffs.first_name, staffs.last_name, staffs.gender, staffs.date_employed, staffs.phone, staffs.user.email, staffs.qualification, staffs.class_in_charge])
        
    return response


class StaffDetailView(DetailView):
    template_name = 'staff/staff_details.html'
    # queryset = StaffProfile.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(StaffProfile, id=id_)


class StaffUpdateView(LoginRequiredMixin, UpdateView):
    form_class = StaffUpdateForm
    template_name = 'staff/staff_update_form.html'
    # queryset = StudentDetail.objects.all()


    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(StaffProfile, id=id_)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

class StaffDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'staff/staff_delete.html'
    success_url = reverse_lazy('staff:staff_list')
    
    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(StaffProfile, id=id_)
    # queryset = StudentDetail.objects.all()

   

@login_required
def staffprofile(request):
    if request.method == 'POST':
        u_form = UserRegisterForm(request.POST,)
        staff_form = StaffRegisterForm(request.POST, request.FILES)
        if u_form.is_valid() and staff_form.is_valid():
            u_form.save()
            staff_form.save()
            messages.success(request, f'New Staff Registered Successfully Please Profile Immediately!')
            return redirect('staff:staff_list')
    else:
        u_form = UserRegisterForm()
        staff_form = StaffRegisterForm()

    context = {
        'u_form': u_form,
        'staff_form': staff_form,
    }

    return render(request, 'staff/staff_register_form.html', context)

staff/templates/staff/my_students.html
{% extends 'portal/portal-home.html'%}
{% load crispy_forms_tags %}
{% load static %}

{% block content_body %}
{% if user.is_authenticated and user.staffprofile.staff_role == 'form_teacher' %}

		<div class="content-body">
			<!-- row -->
			<div class="container-fluid">
				<div class="d-flex justify-content-between align-items-center flex-wrap">
					<div class="card-action coin-tabs mb-2">
						
						<ul class="nav nav-tabs" role="tablist">
							<li class="nav-item">
								<a class="nav-link"href="{% url 'students:student-pdf' %}">View PDF</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'students:student-csv' %}">Download CSV</a>
							</li>
							<li><div>                 
								{% if messages %}
								{% for message in messages %}
								<div class ="alert alert-{{ message.tags }}">{{ message }}</div>
								{% endfor%}
								{% endif%}
							 </div></li>
		
						</ul>
					</div>
					<div class="d-flex align-items-center mb-2 flex-wrap"> 
						<div class="guest-calendar">
							<div id="reportrange" class="pull-right reportrange" style="width: 100%">
								<span>My Students List</span><b class="caret"></b><br>
                               <b>TOTAL in class : {{my_students.count}}</b> 
								
							</div>
						</div>
						<div class="newest ms-3">
							<!-- <select class="default-select"> -->
								<!-- <option><a href="https://google.com">Teacher's List</a></option> -->
								
							</select>
						</div>	
					</div>
				</div>
<!-- 				
					<button class="btn btn-outline-info" > <a href="{% url 'students:student-pdf' %}">PDF Format</a></button>
					<button class="btn btn-outline-info" > <a href="{% url 'students:student-csv' %}">CSV Format</a></button> -->

						<!-- USING FILTER TO GET INFORMATION -->
							<div class="row">
								<div ">	
									<div>
										<!-- <div style="float:left; padding:4px; width:30%;"> -->
											<div>
												
										</div>
									
									  </div>		

									  <!-- END USING FILTER TO GET INFORMATION -->
													
								</div>
								</div>
							
								<div class="col-xl-12">
									<div class="card">
										
										<div class="card-body p-0">
											<div class="tab-content">	
									<div class="tab-pane active show" id="AllGuest">
										<div class="table-responsive">
											<table class="table card-table display mb-4 shadow-hover default-table table-responsive-lg" id="guestTable-all">
												<thead>
													<tr>
														<th class="bg-none">
															<div class="form-check style-1">
															  <input class="form-check-input" type="checkbox" value="" id="checkAll">
															</div>
														</th>
														<th>Student ID</th>
														<th>Admin Date</th>
														<th>Badge</th>
														<th>Profile</th>
														<th>Parent</th>
														<th>Status</th>
													
														
													</tr>
												</thead>
												<tbody>
													{% for s in my_students %}
							
													<tr>
														<td>
															<div class="form-check style-1">
															  <input class="form-check-input" type="checkbox" value="">
															</div>
														</td>
														<td>
															<div class="concierge-bx d-flex align-items-center">
																<img class="me-3 rounded" src="{{s.user.profile.image.url}}" alt="">
																<div>
																	<h5 class="fs-16 mb-0 text-nowrap">
																	<a class="text-black" href="{% url 'students:students-detail' s.pk %}">{{ s.user.username}}- <span style="font-size:9px;, color:grey;">{{s.student_username}}</span></a></h5>
																	<span class="text-primary fs-14">{{ s.first_name}} {{ s.last_name}}</span>
																</div>
															</div>
														</td>
														<td class="text-nowrap">
															<span>{{ s.date_admitted}}</span>
														</td>
														<td>
															<div>
																<h5 class="text-nowrap">{{ s.badge}}</h5>
																
															</div>
														</td>
														<td>
															<div>
																<h5 class="text-nowrap">{{ s.user.profile.code }}</h5>
																<span></span>
															</div>
														</td>
														<td>
														<div>
															<h5 class="text-nowrap">{{ s.guardian_phone }}</h5>
															<span></span>
														</div>
														
														</td>
														
														<td>
															<div>
																{% if s.student_status == 'active' %}
																<span style="color:green"><b>Active</b></span>		
															
																{% elif s.student_status == 'dropped' %}
																<span style="color:red"><b>Dropped</b></span>	
																{% elif s.student_status == 'graduated' %}
																<span style="color:green"><b>Graduated</b></span>	
																{% elif s.student_status == 'expelled' %}
																<span style="color:grey"><b>Expelled</b></span>	
															</div>
																											
															{% endif %}
														</td>	

														{% endfor %}
													</tr>	
												</tbody>
											</table>
										
											<!-- Page Paginator start -->
											{% if studentlist.has_other_pages %}
											{% if studentlist.has_previous %}
											<a class="btn btn-outline-info mb-4" href="?page={{ studentlist.previous_page_number }}">&laquo;</a>
											{% else %}
											<a class="btn btn-outline-info mb-4" href="">&raquo;</a>
	
											{% endif %}
											{% for i in studentlist.paginator.page_range %}
											{% if studentlist.number == i %}
	
											<a class="btn btn-info mb-4" href="">{{ i }}</a>
											{% else %}
											<a class="btn btn-outline-info mb-4" href="?page={{ i }}">{{ i }}</a>
											{% endif %}
											{% endfor %}
											{% if studentlist.has_next %}
											<a class="btn btn-outline-info mb-4" href="?page={{ studentlist.next_page_number }}">&raquo;</a>
											{% else %}
											
											<a class="btn btn-outline-info mb-4" href="">&raquo;</a>
											{% endif %}
										
										{% endif %}
										<!-- Page Paginator end -->
     
										</div>	
									</div>	
									
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
        
{% endif %}

		<!-- ***********************************--> -->



	
		{% endblock content_body %}
		<!--**********************************-->
			
			{% block scripts %}


			<script src="{% static 'portal/vendor/moment/moment.min.js' %}"></script>
    		<script src="{% static 'portal/vendor/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
			<script src="{% static 'portal/vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
			<script src="{% static 'portal/js/plugins-init/datatables.init.js' %}"></script>
	
			<script src="{% static 'portal/vendor/global/global.min.js' %}"></script>
			<script src="{% static 'portal/vendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>
			
			<!-- Apex Chart -->
				<script src="{% static 'portal/vendor/apexchart/apexchart.js' %}"></script>
			
			<!-- Chart piety plugin files -->
			
				<!-- Dashboard 1 -->
			<script src="{% static 'portal/js/dashboard/dashboard-1.js' %}"></script>
			
			<script src="{% static 'portal/vendor/owl-carousel/owl.carousel.js' %}"></script>
			<script src="{% static 'portal/vendor/bootstrap-datetimepicker/js/moment.js' %}"></script>
			<script src="{% static 'portal/vendor/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
			
			<script src="{% static 'portal/js/custom.min.js' %}"></script>
			<script src="{% static 'portal/js/dlabnav-init.js' %}"></script>
			<script src="{% static 'portal/js/demo.js' %}"></script>
			<script src="{% static 'portal/js/styleSwitcher.js' %}"></script>

			{% endblock scripts %}

staff/templates/staff/staff_list.html
{% extends 'portal/portal-home.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}<title> Staff List</title>{% endblock title%}


{% block content_body %}

		<div class="content-body">
			<!-- row -->
			
			<div class="container-fluid">
				<div class="d-flex justify-content-between align-items-center flex-wrap">
					<div class="card-action coin-tabs mb-2">
						
						<ul class="nav nav-tabs" role="tablist">
							<li class="nav-item">
								<!-- <a class="nav-link active"  href="{% url 'staff:staff-pdf' %}">Download PDF</a> -->
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'staff:staff-csv' %}">Download CSV</a>
							</li>
							<li><div>                 
								{% if messages %}
								{% for message in messages %}
								<div class ="alert alert-{{ message.tags }}">{{ message }}</div>
								{% endfor%}
								{% endif%}
							 </div></li>
		
						</ul>

						<div>
							<!-- <div style="float:left; padding:4px; width:30%;"> -->
								<div>
									<form action="" method="get">
								
									<!-- {{ StudentFilter.form|crispy}} -->
									{{ staffprofile_filter.form }}
									
									<button class="btn btn-primary" type="submit">Search </button>
								</form>	</div>
							</div>

					</div>
					<div class="d-flex align-items-center mb-2 flex-wrap"> 
						<div class="guest-calendar">
							<div id="reportrange" class="pull-right reportrange" style="width: 100%">
								<span>Staff List</span><b class="caret"></b>
								<i class="fas fa-user ms-3"></i>
							</div>
						
						</div>
						
					</div>
				</div>
				
					

					<div class="col-xl-12">
						<div class="card">
							<div class="card-body p-0">
								<div class="tab-content">	
									<div class="tab-pane active show" id="AllGuest">
										<div class="table-responsive">
											<table class="table card-table display mb-4 shadow-hover default-table table-responsive-lg" id="guestTable-all">
												<thead>
													<tr>
														<th class="bg-none">
															<div class="form-check style-1">
															  <input class="form-check-input" type="checkbox" value="" id="checkAll">
															</div>
														</th>
														<th>Staff Identity</th>
														<th>Category</th>
														<th>Department</th>
														<th>Phone No.</th>
														<th>Class-in-charge</th>
														<th>Status</th>
														
													</tr>
												</thead>
												<tbody>
													{% for staff in stafflist %}
													<tr>
														<td>
															<div class="form-check style-1">
															  <input class="form-check-input" type="checkbox" value="">
															</div>
														</td>
														<td>
															<div class="concierge-bx d-flex align-items-center">
																<img class="me-3 rounded" src="{{user.profile.image.url}}" alt="">
																<div>
																	<h6 class="fs-16 mb-0 text-nowrap"><a class="text-black" href="{% url 'staff:staff_detail' staff.id %}">{{ staff.user.username}}- <span style="font-size:9px;, color:grey;">{{staff.staff_username}}</span></h6>
																	<span class="text-primary fs-14">{{ staff.first_name}} {{ staff.last_name}}</span></a>
																</div>
															</div>
														</td>
														<td class="text-nowrap">
															<span>{{ staff.user.staffprofile.cat_name}}</span>
														</td>
														<td class="text-nowrap">
															
																<span>{{ staff.user.staffprofile.department}}</span>
																<span></span>
														</td>
														<td class="text-nowrap">
															
																<span>{{ staff.user.staffprofile.phone }}</span>
																<span></span>
														
														</td>
														<td class="text-nowrap">
															<span>{{ staff.user.staffprofile.class_in_charge }}</span>
															<span></span>
														</div>
														
														</td>
														<td>
															<div class="center">
																{% if staff.user.profile.user_type == 'inactive' %}
																<span style="color:red;"><b>Inactive</b></span>
																{% else %}
																<span style="color:green"><b>Active</b></span>
																																																																	
															</div>
															{% endif %}
														</td>
														
														{% endfor %}
													</tr>	
													
												</tbody>
											</table>

											<!-- Page Paginator start -->
			
										{% if stafflist.has_other_pages %}
										{% if stafflist.has_previous %}
										<a class="btn btn-outline-info mb-4" href="?page={{ stafflist.previous_page_number }}">&laquo;</a>
										{% else %}
										<a class="btn btn-outline-info mb-4" href="">&raquo;</a>

										{% endif %}
										{% for i in stafflist.paginator.page_range %}
										{% if stafflist.number == i %}

										<a class="btn btn-info mb-4" href="">{{ i }}</a>
										{% else %}
										<a class="btn btn-outline-info mb-4" href="?page={{ i }}">{{ i }}</a>
										{% endif %}
										{% endfor %}
										{% if stafflist.has_next %}
										<a class="btn btn-outline-info mb-4" href="?page={{ stafflist.next_page_number }}">&raquo;</a>
										{% else %}
										
										<a class="btn btn-outline-info mb-4" href="">&raquo;</a>
										{% endif %}
									
									{% endif %}
									<!-- Page Paginator end -->

									</div>	
									</div>	
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
		{% endblock content_body %}
		<!--**********************************
			

staff/templates/staff/staff_profile.html
{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" alt="">
        <div class="media-body">
            
        </div>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Staff Profile & Academic Information</legend>
         
            {{ aca_form.as_p }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>
       

</div>

{% endblock content %}