blog/urls.py
from django.urls import path
from .views import (
    PostDetailView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
   
    
)
from blog import views as blog_views


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='blog_home'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('like/<int:pk>', blog_views.LikeView, name='like_post'),
    
]

payment/urls.py
from django.urls import path
from payment import views as payment_views
from payment.views import PaymentCreateView
from . import views



app_name = 'payment'

urlpatterns = [
    path('payment-form/', payment_views.payment_form, name="payment_form"),   
    path('payment-report/', payment_views.payment_report, name="payment_report"),
    # path('summary-payment-report/', payment_views.summary_payment_report, name="summary_payment_report"),
    path('debtor-list/', payment_views.debtor_list, name="debtor_list"),      
    path('payment-cat-form/', payment_views.payment_cat_form, name="payment_cat_form"),
    path('payment-chart-form/', payment_views.payment_chart_form, name="payment_chart_form"),
    path('payment-record/', payment_views.paymentlist, name="payment_record"),
    path('payment-chart/', payment_views.payment_chart_list, name="payment_chart"),
    path('my-payments/', payment_views.view_self_payments, name="my_payments"),
    # path('mypayment/', views.MypaymentListView.as_view(), name='mypayment_list'),
    # path('make-payment/', payment_views.make_payments, name="make_payment"),
    path('payment-pdf', payment_views.allpayment_pdf, name="payment-pdf"),
    path('payment-csv', payment_views.allpayment_csv, name="payment-csv"),
    path('debtor-csv', payment_views.debtor_csv, name="debtor-csv"),
    path('payment_chart-pdf', payment_views.payment_chart_pdf, name="payment_chart-pdf"),
    path('payment_chart-csv', payment_views.payment_chart_csv, name="payment_chart-csv"),

    path('payment-create/', views.PaymentCreateView.as_view(), name="payment-create"),
    path('<int:pk>/', views.PaymentDetailView.as_view(), name='payment_detail'),
    path('payment-category/', views.PaymentCategoryListView.as_view(), name='payment-category'),
    path('bank-list/', views.BankListView.as_view(), name='bank-list'),
    path('bank-create/', views.BankCreateView.as_view(), name="bank-create"),
       
    path('<int:pk>/payment_update', views.PaymentUpdateView.as_view(), name='payment_update'),

    # Search student detail app
    path('payment-search/', payment_views.payment_search_list, name='payment_search_list'),
    path('search/', payment_views.search, name='search'),

    # render receipt as pdf
    path('pdf/<pk>/', payment_views.receipt_render_pdf_view, name="receipt-pdf-view"),
]

portal/urls.py
from django.urls import path
from portal import views as portal_views 
from . import views


app_name = 'portal'

urlpatterns = [
    path('home/', portal_views.portal_home, name="portal-home"),
    path('register-class/', portal_views.register_new_standard, name="register-class"),
    path('register-class-section/', portal_views.register_new_classgroup, name="register-classgroup"),
    path('register-new-session/', portal_views.register_new_session, name="register-session"),
    path('register-new-category/', portal_views.register_new_category, name="register-category"),
    path('register-new-department/', portal_views.register_new_department, name="register-department"),
    path('register-new-subject/', portal_views.register_exam_subjects, name="register-subject"),
    path('register-exam/', portal_views.register_exam, name="register-exam"),
    path('<int:pk>/', views.StudentCardDetailView.as_view(), name='my_idcard'),

    path('category-list/', views.CategoryListView.as_view(), name="category_list"),
    path('department-list/', views.DepartmentListView.as_view(), name="department_list"),
    path('subjects-list/', views.SubjectListView.as_view(), name="subject_list"),
    path('exam-list/', views.ExamListView.as_view(), name="exam_list"),
    path('session-list/', views.SessionListView.as_view(), name="session_list"),
    path('class-group-list/', views.ClassGroupListView.as_view(), name="classgroup_list"),
    path('exam/', portal_views.set_exam, name='set-exam'), 
   


]

schoolly/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
#from django.conf.urls import url
from django.views.static import serve


# from attendance.views import AttendanceAutocomplete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('curriculum/', include('curriculum.urls', namespace='curriculum')),
    path('', include('pages.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('users/', include('users.urls')),
   
    path('results/', include('results.urls', namespace='results')),
    path('students/', include('students.urls', namespace='students')),
    path('staff/', include('staff.urls', namespace='staff')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    # path('demoschool/', include('demoschool.urls', namespace='demoschool')),
    path('portal/', include('portal.urls', namespace='portal')),
    path('quizes/', include('quizes.urls', namespace = 'quizes')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('notification/', include('notification.urls', namespace = 'notification')),
    path('inventory/', include('inventory.urls', namespace = 'inventory')),
    path('quiz_results/', include('quiz_results.urls', namespace = 'quiz_results')),
    # path('demoschool/', include('demoschool.urls')),
   

    # path('ckeditor', include('ckeditor_uploader.urls')),    #for ckeditor image upload
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    


    

#PATH FOR DOWNLOAD URL
   #url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
   #path(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),


#    url( r'^attendance-autocomplete/$', AttendanceAutocomplete.as_view(), name='attendance-autocomplete',
#     ),

  path('djrichtextfield/', include('djrichtextfield.urls')),

# for django-rest-framework
#   path('api-auth/', include('rest_framework.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from curriculum.models import Session
from students.models import StudentDetail
from django.conf import settings
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator 
from django.db.models import F, Sum, Q


class BankDetail(models.Model):
    acc_name = models.CharField(max_length=150, blank=False)
    acc_number = models.CharField(max_length=20, blank=False)
    description = models.CharField(max_length=150, blank=False, verbose_name='Bank Name')

    def __str__(self):
        return f'{self.acc_number} - {self.description}'

    class Meta:
        ordering:['acc_number']


class PaymentCategory(models.Model):
    name = models.CharField(max_length=150, blank=True, unique=True)
    description = models.CharField(max_length=150, blank=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Payment Category'
        verbose_name_plural = 'Payment Categories'


class PaymentChart(models.Model):
    name = models.CharField(max_length=150, blank=True)
    payment_cat = models.ForeignKey(PaymentCategory, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)

    first_term = 'First Term'
    second_term = 'Second Term'
    third_term = 'Third Term'
    others = 'Others'

    term = [
        (first_term, 'First Term'),
        (second_term, 'Second Term'),
        (third_term, 'Third Term'),
        (others, 'Others'),
    ]
    term = models.CharField(max_length=50, choices=term, blank=True) 
    amount_due = models.DecimalField(max_digits=15, decimal_places=2, default=0.0) 
    
    def __str__ (self):
        return f'{self.name}' 

    class Meta:
        ordering:['-session']
    

class PaymentDetail(models.Model):
    student_detail = models.ForeignKey(StudentDetail, on_delete=models.CASCADE, default=None, null=True)
    student_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None, null=True,  help_text='confirm student username', related_name='student_detail')
    payment_name = models.ForeignKey(PaymentChart, on_delete=models.CASCADE, default= None, related_name='payment_name')
    amount_paid_a = models.DecimalField(max_digits=15, decimal_places=2, default=0.0, null=True, help_text='First Payment Amount')
    bank_name_a = models.ForeignKey(BankDetail, on_delete=models.CASCADE, default=None, null=True, related_name='bank_name_a')   
    payment_date_a = models.DateField()
    other_details_a = models.CharField(max_length=200, blank=True, verbose_name='description(if any)')

    amount_paid_b = models.DecimalField(max_digits=15, decimal_places=2, default=0.0, null=True, help_text='Second Payment Amount')
    bank_name_b = models.ForeignKey(BankDetail, on_delete=models.CASCADE, default=None, null=True, blank=True, related_name='bank_name_b')   
    payment_date_b = models.DateField(blank=True, null=True)
    other_details_b = models.CharField(max_length=200, blank=True, verbose_name='description(if any)')

    amount_paid_c = models.DecimalField(max_digits=15, decimal_places=2, default=0.0, null=True, help_text='Third Payment Amount')
    bank_name_c = models.ForeignKey(BankDetail, on_delete=models.CASCADE, default=None, null=True, blank=True)   
    payment_date_c = models.DateField(blank=True, null=True)
    other_details_c = models.CharField(max_length=200, blank=True, verbose_name='description(if any)')

    discount = models.DecimalField(help_text='enter in (%) leave empty if no discoun is given', max_digits=3, decimal_places=0, blank=True, null=True, verbose_name='TOTAL DISCOUNT(if any)', default=0, validators=[MinValueValidator(0), MaxValueValidator(100)]) 
    # payment confirmation
    confirmed_a = models.BooleanField(default=False) 
    confirmed_b = models.BooleanField(default=False) 
    confirmed_c = models.BooleanField(default=False) 

    payment_updated_date = models.DateField(auto_now_add=True)     

    class Meta:
        ordering = ['-student_detail' ]

        unique_together = ['student_detail', 'payment_name']

        

    def __str__ (self):
       return f'{self.student_detail} {self.student_id} '

    def get_absolute_url(self):
        return reverse('payment:my_payments')  
    
    # def get_absolute_url(self):
    #     return reverse('payment:payment_detail', kwargs={'id':self.id})
    
       

    @property
    def balance_pay(self):
       return self.payment_name.amount_due - (self.amount_paid_a + self.amount_paid_b + self.amount_paid_c)
    
    @property
    def total_amount_paid(self):
       return (self.amount_paid_a + self.amount_paid_b + self.amount_paid_c)

    @property
    def discounted_amount_due(self):
       return self.payment_name.amount_due - (self.discount/100 * self.payment_name.amount_due)
    

    @property
    def discounted_balance_pay(self):
        #return self.discounted_amount_due - self.amount_paid
        return self.discounted_amount_due - self.total_amount_paid
    
    # for getting total balance to pay if discounted
    @property
    def discounted_balance_owed(self):
        #return self.discounted_amount_due - self.amount_paid
        return self.discounted_amount_due - (self.amount_paid_a + self.amount_paid_b + self.amount_paid_c )
    
    
    # if student has CREDIT without discount
    @property
    def credit_balance(self):
        #return self.discounted_amount_due - self.amount_paid
        return self.total_amount_paid - self.payment_name.amount_due
    
        # if student has CREDIT and is dicounted
    @property
    def credit_balance_discounted(self):        
        return self.total_amount_paid - self.discounted_amount_due
    
    @property
    def discounted_amount(self):
        return self.payment_name.amount_due - self.discounted_balance_pay


    # for getting total number of payments a student made
    @property
    def no_of_payments(request):
      return PaymentDetail.objects.filter(student_detail = request.student_detail).count()
    
    @property
    def studentdetail(self):
       return self.student_detail

       
    

payment/forms.py
from django import forms
from payment.models import PaymentDetail, PaymentCategory, PaymentChart, BankDetail

# INLINE FORM STUFF
from django import forms
from django.forms.models import formset_factory
from crispy_forms.helper import FormHelper
from crispy_forms import layout, bootstrap
from crispy_forms.bootstrap import InlineField, FormActions, StrictButton, Div
from crispy_forms.layout import Layout
from crispy_forms import bootstrap, layout


class PaymentChartForm(forms.ModelForm):
    """
    TODO: Extend CompanyModel into Form
    :returns: TODO
    """
    def __init__(self, *args, **kwargs):
        super(PaymentChartForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.method = "POST"
        self.helper.form_class = 'form-inline'
        self.helper.field_template = 'bootstrap3/layout/inline_field.html'
        self.helper.form_action = "payment:payment-chart"

        self.helper.layout = Layout(
        Div(
            Div('name', css_class="col-sm-2"),
            Div('payment_cat', css_class="col-sm-2"),
            Div('session', css_class="col-sm-2"),
            # Div('term', css_class="col-sm-2"),
            Div('amount_due', css_class="col-sm-2"),
            bootstrap.FormActions(
                layout.Submit('submit', 'Add', css_class='btn btn-primary')),
            css_class='row',
        )
    )

    class Meta:
        model = PaymentChart
        fields = ["name", "payment_cat", "session", "term", "amount_due"]



class PaymentCreateForm(forms.ModelForm):
        
        class Meta:
            model = PaymentDetail
            fields = '__all__'
            exclude = ('confirmed_a', 'confirmed_b', 'confirmed_c', 'discount', 'student_id', 'student_detail',)

            widgets = {
            'payment_date_a': forms.DateInput(
                format=('%d/%m/%Y'),
                attrs={'class': 'form-control', 
                       'placeholder': 'Select a date',
                       'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                      }),
        }
                        #Note that i removed user because it is an instance in the view already
                        

class PaymentForm(forms.ModelForm):
        
        class Meta:
            model = PaymentDetail
            fields = '__all__'
            exclude = ('confirmed', 'file',)

            widgets = {
            'payment_date': forms.DateInput(
                format=('%d/%m/%Y'),
                attrs={'class': 'form-control', 
                       'placeholder': 'Select a date',
                       'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                      }),
        }
                        #Note that i removed user because it is an instance in the view already



          
class PaymentCatForm(forms.ModelForm):
        
        class Meta:
            model = PaymentCategory
            fields = '__all__'
           

class BankRegisterForm(forms.ModelForm):
        
        class Meta:
            model = BankDetail
            fields = '__all__'


class PaymentUpdateForm(forms.ModelForm):
        
        class Meta:
            model = PaymentDetail
            fields = '__all__'
            exclude = ('confirmed', 'discount', 'file', 'student_id', 'student_detail',)

            widgets = {
            'payment_date_a' 'payment_date_b': forms.DateInput(
                format=('%d/%m/%Y'),
                attrs={'class': 'form-control', 
                       'placeholder': 'Select a date',
                       'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                      }),
        }
                        #Note that i removed user because it is an instance in the view already

payment/templates/payment/bank_list.html
{% extends 'portal/portal-home.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}<title>Bank Detail List </title>{% endblock title %}

{% block content_body %}
<div class="content-body">
    <div class="container-fluid">
        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href=""><span style="font-size: 35px;"><h3> Bank Detail List</h3></span></a></li>
                
                
            </ol>
        </div>
        <!-- row -->
        <div class="row">
            <div class="col-xl-10 col-xxl-10 col-lg-10">
                <div class="card">
                 
                    <div class="card-body">
                        <div id="DZ_W_TimeLine" class="widget-timeline dlab-scroll height770">
                            {% if user.is_authenticated %}
                        
                            {% for bk in banklist %}    
                               <ul>                                             
                              <li> <span style="font-size:16px;">Acc. Name: <strong>{{ bk.acc_name}}</strong><br>
                                 <span style="color:grey;"> Acc. No.: <strong> {{ bk.acc_number}} </strong></span> <br>
                                 <span style="font-size:16px; color:rgba(0, 0, 255, 0.541);"> Bank Name: <strong>{{ bk.description}}</strong></span>
                                <hr>
                                </li>
                            </ul>  
                              
                                                             
                                {% endfor %}                                                   
                          
                       {% else %}
                        <div>
                            <h1>Permission Denied!</h1>
                        </div>
                      
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            </div>
            </div>
            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content_body %}

payment/templates/payment/payment_report_table.html
{% extends 'portal/portal-home.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}<title> Payment Report</title>{% endblock title%}

{% block content_body %}
{% if user.is_authenticated and user.is_superuser or user.profile.user_type == "admin" %}

		<div class="content-body">
			<!-- row -->
			<div class="container-fluid">
				<div class="d-flex justify-content-between align-items-center flex-wrap">
					<div class="card-action coin-tabs mb-2">
						
						<!-- <ul class="nav nav-tabs" role="tablist"> -->
							<!-- <li class="nav-item">
								<a class="nav-link"href="{% url 'payment:payment-pdf' %}">View PDF</a>
							</li> -->
							<!-- <li class="nav-item">
								<a class="nav-link" href="{% url 'payment:payment-csv' %}">Download CSV</a> -->
							<!-- </li>
						</ul> -->
					</div>
					<div class="d-flex align-items-center mb-2 flex-wrap"> 
						<!-- <span><a class="nav-link" href="{% url 'payment:payment-csv' %}"><strong>>> Download CSV</strong></a></span> -->
						<div class="guest-calendar">
							<div id="reportrange" class="pull-right reportrange" style="width: 100%">
								<span>Detail Payment Report - - - </span><b class="caret"></b>
								<!-- <i class="fas fa-user ms-3"></i> -->
								<button class="btn btn-primary"><a href="{% url 'payment:payment_search_list' %}" style="color:azure;">Search For Payments </a></button> ---
								<button class="btn btn-primary"><a href="{% url 'payment:payment-csv' %}" style="color:azure;">DOWNLOAD TO EXCEL </a></button>


							</div>
						</div>
						<div class="newest ms-3">
	
							</select>
						</div>	
					</div>
				</div>

                <!-- USING FILTER TO GET INFORMATION -->
                    <div class="row">
                        <div>	
                            <div>
                                <!-- <div style="float:left; padding:4px; width:30%;"> -->
                                    <!-- <div> -->
										<!-- <button class="btn btn-primary">Search For Payments </button> -->
                                        <!-- <form action="" method="get"> -->
                                    
                                        <!-- {{ StudentFilter.form|crispy}} -->
                                        <!-- {{ paymentreport_filter.form }} -->
                                       
                                        <!-- <button class="btn btn-primary" type="submit">Search </button> -->
										<!-- <button class="btn btn-primary" type="submit">Download To EXCEL </button> -->
                                    <!-- </form>	</div> -->
                                <!-- </div> -->
                            
                                </div>		

                                <!-- END USING FILTER TO GET INFORMATION -->    
			
					</div>
					</div>
					
				
					<div class="col-xl-12">
						<div class="card">
							
							<div class="card-body p-0">
								<div class="tab-content">	
									<div class="tab-pane active show" id="AllGuest">
										<div class="table-responsive">
											<table class="table card-table display mb-4 shadow-hover default-table table-responsive-lg" id="guestTable-all">
												<thead style= color:green;">
													<tr>
														<th class="bg-none">
															<div class="form-check style-1">
															  <input class="form-check-input" type="checkbox" value="" id="checkAll">
															</div>
														</th>
														<th>NO</th>
														<th>STUDENT</th>
                                                        <th>DESCRIPTION</th>                                                        
														<th>FEE DUE</th>
														<th>AMOUNT PAID</th>
														<th>DEBT/CREDIT</th>                                                        
														<!-- <th>INST. </th> -->
                                                        <th>PAYMENT METHOD</th>
														<th>ACTION</th>
														
													</tr>
												</thead>
												<tbody>
                                                   
                                                    {% for balance in paymentlist %}
								
													<tr>
																												
														<td>
															<div class="form-check style-1">
															  <input class="form-check-input" type="checkbox" value="">
															</div>
														</td>
														
														<td>
															<div>
																{{ forloop.counter }}
															</div>
														</td>	
														
														<td>
													
															<span class="fs-16 mb-0 text-nowrap"><a class="text-black" href="{% url 'payment:payment_detail' pk=balance.pk %}">
																<!-- if it is a student that paid -->
																 {% if balance.student_id  %}
																<span>{{ balance.student_id.studentdetail.first_name }} {{ balance.student_id.studentdetail.last_name}}</span><br>{{balance.student_id }}
																{% else %}
																<span> {{balance.student_detail.first_name }} {{balance.student_detail.first_name }}</span><br>{{balance.student_detail.student_username }}
																{% endif %}
																</span>
																
											
																</div>
															</div>
														</td>
														
														<td class="text-nowrap">
															<!-- if admin or other person paid for students -->
															<span class="text-nowrap">{{ balance.payment_name.name }}</span><br>
                                                            <span><strong>{{ balance.payment_name.term}} - {{ balance.payment_name.session}}</strong></span>

                                                            </td>
															<!-- if students paid by themselves -->
															{% if balance.discount %}
                                                        <td class="text-nowrap">                                                
                                                            <span class="text-nowrap">Discount: {{balance.discount}}%<br>N {{ balance.discounted_amount_due |floatformat:2 }}</span>
                                                            </td>
															{% else %}
															<td class="text-nowrap">                                                
																<span class="text-nowrap">N {{ balance.payment_name.amount_due }}</span>
																</td>
															{% endif %}

                                                        <td class="text-nowrap">
															<span class="text-nowrap">N{{ balance.amount_paid_a }} - {{ balance.payment_date_a }} <br>
																 N{{ balance.amount_paid_b }} - {{ balance.payment_date_b }} <br>
																N{{ balance.amount_paid_c }} - {{ balance.payment_date_c }} </span>
                                                            <!-- <span>{{ balance.payment_date_a }}, {{ balance.payment_date_b }}, {{ balance.payment_date_c }}</span> -->
														
														</td>
														
														<td class="text-nowrap">
															<!-- Payment with discount -->

															{% if balance.discount %}
															{% if balance.total_amount_paid == balance.discounted_amount_due %}
															<span class="text-nowrap" style="color: green;"> You Paid In full <br></span>

															{% elif balance.discounted_amount_due > balance.total_amount_paid %}
															<span class="text-nowrap" style="color: red;"> DEBT: <br>N{{ balance.discounted_balance_pay |floatformat:2}}</span>
															
															{% elif balance.total_amount_paid > balance.discounted_amount_due  %}
															<span class="text-nowrap" style="color: green;"> CREDIT: <br>N{{ balance.credit_balance_discounted |floatformat:2}}</span>

															{% else %}
															<span class="text-nowrap">You've not made any payment</span>
															{% endif %}
															{% endif %}
															
															<!-- Payment without discount -->

															{% if balance.discount == False %}
															{% if balance.total_amount_paid == balance.payment_name.amount_due %}
															<span class="text-nowrap" style="color: green;"> You Paid In full <br></span>
																												
															{% elif balance.total_amount_paid > balance.payment_name.amount_due %}
															<span class="text-nowrap" style="color: green;">CREDIT: <br>{{ balance.credit_balance|floatformat:2 }}</span>
																																					
															{% else %}
															<span class="text-nowrap" style="color: red;">DEBIT: <br>{{ balance.balance_pay}}</span>
															{% endif %}
															{% endif %}
															
														</td>
														
														<td class="text-nowrap">
															
																<span class="text-nowrap" style="color:green;">{{ balance.bank_name_a }} <br>{{ balance.bank_name_b }} <br>{{ balance.bank_name_c }}</span>

																<span></span>
																</td>
												
														
														<td class="text-nowrap">
															<div>
																<span> <a class =" btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'payment:payment_update' pk=balance.pk %}"> Update</a></span>
																
															</div>
																									
															</td>
															
														</tr>	
														{% endfor %}
												</tbody>
											</table>								

                                            
										{% if paymentlist.has_other_pages %}
										{% if paymentlist.has_previous %}
                                            <a class="btn btn-outline-info mb-4" href="?page={{ paymentlist.previous_page_number }}">&laquo;</a>
                                        {% else %}
                                            <a class="btn btn-outline-info mb-4" href="">&raquo;</a>

										{% endif %}

										{% for i in paymentlist.paginator.page_range %}
										{% if paymentlist.number == i %}

										    <a class="btn btn-info mb-4" href="">{{ i }}</a>
										{% else %}
										    <a class="btn btn-outline-info mb-4" href="?page={{ i }}">{{ i }}</a>
										{% endif %}
										{% endfor %}
										
                                        {% if paymentlist.has_next %}
										    <a class="btn btn-outline-info mb-4" href="?page={{ paymentlist.next_page_number }}">&raquo;</a>
										{% else %}
										
										    <a class="btn btn-outline-info mb-4" href="">&raquo;</a>
										{% endif %}
									
									{% endif %}
									<!-- Page Paginator end -->


										</div>	
									</div>	
									
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
        
        {% endif %}

		<!-- ***********************************--> -->

	
		{% endblock content_body %}
		<!--**********************************-->
			
			{% block scripts %}

			<script src="{% static 'portal/vendor/moment/moment.min.js' %}"></script>
    		<script src="{% static 'portal/vendor/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
			<script src="{% static 'portal/vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
			<script src="{% static 'portal/js/plugins-init/datatables.init.js' %}"></script>
	
            <script src="{% static 'portal/vendor/global/global.min.js' %}"></script>

            <script src="{% static 'portal/vendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>
            
            <!-- Apex Chart -->
            <script src="{% static 'portal/vendor/apexchart/apexchart.js' %}"></script>
            
            <!-- Chart piety plugin files -->
            <!-- Dashboard 1 -->
            <script src="{% static 'portal/js/dashboard/dashboard-1.js' %}"></script>
            
            <script src="{% static 'portal/vendor/owl-carousel/owl.carousel.js' %}"></script>
            <script src="{% static 'portal/vendor/bootstrap-datetimepicker/js/moment.js' %}"></script>
            <script src="{% static 'portal/vendor/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
            
            <script src="{% static 'portal/js/custom.min.js' %}"></script>
            <script src="{% static 'portal/js/dlabnav-init.js' %}"></script>
            <script src="{% static 'portal/js/demo.js' %}"></script>
            <script src="{% static 'portal/js/styleSwitcher.js' %}"></script>

{% endblock scripts %}